#pragma once

#include <vector>
#include <string>

// =============================================================================
// Step 10 Phase B — Profiling Prompt Set
// =============================================================================
// 500+ diverse, general-purpose prompts that exercise different neuron
// activation patterns. The hot set is stable across domains, so diversity
// is more important than domain depth.
//
// Categories: General Knowledge, Code, Math, Science, Language, Philosophy,
// Creative, Analysis, Technical, Practical, History, Geography, Art, Music,
// Business, Health, Environment, Education, Psychology, Sociology
// =============================================================================

std::vector<std::string> get_profiling_prompts() {
    return {
        // === General Knowledge (50) ===
        "Explain the process of photosynthesis in simple terms.",
        "What are the main causes of climate change?",
        "How does the human immune system work?",
        "Describe the history of the Roman Empire.",
        "What is quantum computing and how does it differ from classical computing?",
        "Explain the theory of evolution by natural selection.",
        "What is the greenhouse effect and why does it matter?",
        "How does the internet work at a high level?",
        "What are tectonic plates and how do they move?",
        "Explain the water cycle in detail.",
        "What is dark matter and why do scientists think it exists?",
        "How does nuclear fusion power the sun?",
        "What is the speed of light and why is it a universal limit?",
        "Explain the concept of entropy in thermodynamics.",
        "What is the Big Bang theory?",
        "How do vaccines train the immune system?",
        "What is CRISPR gene editing?",
        "Explain how GPS satellites determine your location.",
        "What is the difference between weather and climate?",
        "How do black holes form?",
        "What is the metric system and why was it created?",
        "Explain the structure of an atom.",
        "What is photosynthesis and why is it important for life?",
        "How does the human brain process memory?",
        "What is the Internet of Things?",
        "Explain the concept of supply and demand.",
        "What are renewable energy sources?",
        "How does electricity reach your home?",
        "What is the periodic table of elements?",
        "Explain how sound travels through air.",
        "What is the difference between DNA and RNA?",
        "How do antibiotics work against bacteria?",
        "What is the ozone layer and why is it important?",
        "Explain the concept of gravity.",
        "What are plate boundaries and what happens at each type?",
        "How does the human circulatory system work?",
        "What is the speed of sound and what affects it?",
        "Explain the difference between renewable and non-renewable resources.",
        "What is the carbon cycle?",
        "How do fossils form?",
        "What is the food chain and food web?",
        "Explain the greenhouse effect vs global warming.",
        "What is biodiversity and why does it matter?",
        "How does the Earth's magnetic field protect us?",
        "What are the layers of the Earth's atmosphere?",
        "Explain how volcanoes erupt.",
        "What is the difference between a hurricane, tornado, and cyclone?",
        "How does the human digestive system work?",
        "What is the difference between bacteria and viruses?",
        "Explain the concept of natural selection.",
        
        // === Code & Programming (50) ===
        "Write a Python function to sort a list using quicksort.",
        "Explain the difference between a stack and a queue.",
        "What is a hash table and how does it handle collisions?",
        "Write a SQL query to find top customers by purchase amount.",
        "How does garbage collection work in Java?",
        "Explain the difference between TCP and UDP.",
        "Write a binary search algorithm in C++.",
        "What is a REST API and how does it work?",
        "Explain the difference between threads and processes.",
        "Write a Python decorator that times function execution.",
        "What is dependency injection and why is it useful?",
        "Explain the MVC architectural pattern.",
        "Write a regex to validate email addresses.",
        "What is a linked list and when should you use one?",
        "Explain the difference between deep and shallow copy.",
        "Write a function to check if a string is a palindrome.",
        "What is the difference between SQL and NoSQL databases?",
        "Explain how a blockchain works.",
        "Write a Python context manager for file handling.",
        "What is event-driven programming?",
        "Explain the difference between inheritance and composition.",
        "Write a function to flatten a nested list.",
        "What is a design pattern and name three common ones?",
        "Explain the CAP theorem in distributed systems.",
        "Write a Python generator for Fibonacci numbers.",
        "What is the difference between a compiler and an interpreter?",
        "Explain how DNS resolves domain names.",
        "Write a function to find the longest common subsequence.",
        "What is memoization and when should you use it?",
        "Explain the difference between乐观锁 and 悲观锁.",
        "Write a Python class implementing a stack.",
        "What is a microservice architecture?",
        "Explain the difference between vertical and horizontal scaling.",
        "Write a function to rotate a matrix 90 degrees.",
        "What is the difference between HTTP and HTTPS?",
        "Explain how load balancing works.",
        "Write a Python script to parse JSON data.",
        "What is a trie data structure?",
        "Explain the difference between processes and coroutines.",
        "Write a function to detect a cycle in a linked list.",
        "What is the difference between REST and GraphQL?",
        "Explain how caching improves performance.",
        "Write a Python function to merge two sorted arrays.",
        "What is the difference between a mutex and a semaphore?",
        "Explain the observer design pattern.",
        "Write a function to check if a binary tree is balanced.",
        "What is containerization vs virtualization?",
        "Explain the difference between TCP/IP and OSI models.",
        "Write a function to implement a LRU cache.",
        "What is the difference between agile and waterfall?",
        
        // === Mathematics (50) ===
        "Prove that the square root of 2 is irrational.",
        "Explain eigenvalues and eigenvectors.",
        "What is the fundamental theorem of calculus?",
        "Describe the Euclidean algorithm for GCD.",
        "What is a Fourier transform used for?",
        "Explain the concept of a limit in calculus.",
        "What is the difference between correlation and causation?",
        "Explain Bayes' theorem with an example.",
        "What is the Monte Carlo method?",
        "Describe the simplex algorithm for linear programming.",
        "What is the difference between permutations and combinations?",
        "Explain the concept of a derivative.",
        "What is the Riemann hypothesis about?",
        "Describe how the Newton-Raphson method finds roots.",
        "What is the difference between discrete and continuous math?",
        "Explain the concept of a matrix determinant.",
        "What is the Fibonacci sequence and where does it appear?",
        "Describe the concept of mathematical induction.",
        "What is the difference between a series and a sequence?",
        "Explain the concept of a probability distribution.",
        "What is the normal distribution and the central limit theorem?",
        "Describe the concept of a vector space.",
        "What is group theory and why is it important?",
        "Explain the difference between open and closed sets.",
        "What is the pigeonhole principle?",
        "Describe the concept of a topological space.",
        "What is the difference between countable and uncountable infinity?",
        "Explain the concept of a graph in mathematics.",
        "What is Euler's formula for polyhedra?",
        "Describe the concept of a mathematical proof.",
        "What is the difference between a field and a ring?",
        "Explain the concept of a tensor.",
        "What is the imaginary number i and how is it used?",
        "Describe the concept of a differential equation.",
        "What is the Laplace transform used for?",
        "Explain the concept of a metric space.",
        "What is the difference between a function and a relation?",
        "Describe the concept of a manifold.",
        "What is the Banach fixed-point theorem?",
        "Explain the concept of a measure in mathematics.",
        "What is the difference between pointwise and uniform convergence?",
        "Describe the concept of a Hilbert space.",
        "What is the Cauchy-Schwarz inequality?",
        "Explain the concept of a convex set.",
        "What is Jensen's inequality?",
        "Describe the concept of a Markov chain.",
        "What is the difference between deterministic and stochastic processes?",
        "Explain the concept of a random variable.",
        "What is the law of large numbers?",
        "Describe the concept of a generating function.",
        
        // === Science (50) ===
        "Explain the theory of relativity in plain language.",
        "How do vaccines work at a molecular level?",
        "Describe the process of DNA replication.",
        "What causes earthquakes and how are they measured?",
        "Explain the water cycle's importance to ecosystems.",
        "How does photosynthesis convert light to energy?",
        "What is the human genome project?",
        "Explain the difference between mitosis and meiosis.",
        "How do stars form and die?",
        "What is the standard model of particle physics?",
        "Explain how lasers work.",
        "What is the second law of thermodynamics?",
        "How does the brain's neural network process information?",
        "What is stem cell research?",
        "Explain the process of nuclear fission.",
        "How do planets form in a solar system?",
        "What is the greenhouse effect at a molecular level?",
        "Explain how antibodies fight infections.",
        "What is the Heisenberg uncertainty principle?",
        "How does evolution produce new species?",
        "What is the difference between chemistry and biochemistry?",
        "Explain the concept of a chemical bond.",
        "How do neurotransmitters communicate between neurons?",
        "What is the role of mitochondria in cells?",
        "Explain the concept of half-life in radioactive decay.",
        "How does the immune system develop memory?",
        "What is the difference between RNA and DNA viruses?",
        "Explain the process of protein synthesis.",
        "How do telescopes capture images of distant galaxies?",
        "What is the cosmic microwave background radiation?",
        "Explain the concept of a catalyst in chemistry.",
        "How do antibiotics become less effective over time?",
        "What is the difference between weathering and erosion?",
        "Explain the process of crystallization.",
        "How does the human eye perceive color?",
        "What is the role of enzymes in biological reactions?",
        "Explain the concept of osmosis.",
        "How do magnets work at the atomic level?",
        "What is the difference between acids and bases?",
        "Explain the process of combustion.",
        "How does the endocrine system regulate hormones?",
        "What is the role of chlorophyll in plants?",
        "Explain the concept of pH and its importance.",
        "How do bacteria develop resistance to antibiotics?",
        "What is the difference between speed and velocity?",
        "Explain the concept of work in physics.",
        "How does the human body maintain homeostasis?",
        "What is the role of white blood cells?",
        "Explain the concept of electrical resistance.",
        "How do weather patterns form in the atmosphere?",
        
        // === Language & Linguistics (50) ===
        "What are the differences between Spanish and Portuguese?",
        "How does language evolution work over centuries?",
        "Explain the concept of linguistic relativity.",
        "What makes a language a dialect vs separate language?",
        "How do tonal languages like Mandarin work?",
        "What is the difference between syntax and semantics?",
        "Explain how children acquire their first language.",
        "What are the Indo-European language family branches?",
        "How does loanword borrowing work between languages?",
        "What is the Sapir-Whorf hypothesis?",
        "Explain the difference between phonemes and allophones.",
        "How do writing systems evolve from pictographs?",
        "What is the role of grammar in communication?",
        "Explain the concept of a morpheme.",
        "How do creole languages form?",
        "What is the difference between prescriptive and descriptive grammar?",
        "Explain how sign languages work.",
        "What are the levels of linguistic analysis?",
        "How does language change over time?",
        "What is the difference between a language and a protocol?",
        "Explain the concept of pragmatics in language.",
        "How do endangered languages get preserved?",
        "What is the role of prosody in speech?",
        "Explain the difference between connotation and denotation.",
        "How does translation handle untranslatable concepts?",
        "What is the universal grammar hypothesis?",
        "Explain the concept of a speech act.",
        "How do languages handle gendered nouns?",
        "What is the difference between active and passive voice?",
        "Explain the concept of linguistic anthropology.",
        "How does code-switching work in bilingual speakers?",
        "What is the role of metaphor in language?",
        "Explain the difference between formal and informal registers.",
        "How do pidgin languages develop?",
        "What is the concept of linguistic typology?",
        "Explain how orthography standardization works.",
        "What are the challenges of machine translation?",
        "How do languages express time and tense?",
        "What is the difference between a corpus and a lexicon?",
        "Explain the concept of a language family tree.",
        "How does language contact influence vocabulary?",
        "What is the role of accent in social identity?",
        "Explain the difference between oral and written traditions.",
        "How do languages handle number and quantity?",
        "What is the concept of linguistic diversity?",
        "Explain how alphabets differ from logographic systems.",
        "What is the role of context in language understanding?",
        "How does language influence thought patterns?",
        "What is the difference between competence and performance in linguistics?",
        "Explain the concept of a phonological rule.",
        
        // === Philosophy (50) ===
        "What is the trolley problem in ethics?",
        "Explain Plato's allegory of the cave.",
        "What is existentialism and who are its key thinkers?",
        "Discuss the mind-body problem in philosophy.",
        "What is the difference between morality and ethics?",
        "Explain the concept of free will vs determinism.",
        "What is utilitarianism and how does it work?",
        "Discuss the philosophy of science.",
        "What is the difference between empiricism and rationalism?",
        "Explain Kant's categorical imperative.",
        "What is nihilism and why is it philosophically significant?",
        "Discuss the philosophy of language.",
        "What is the difference between ontology and epistemology?",
        "Explain the concept of a thought experiment.",
        "What is the prisoner's dilemma?",
        "Discuss the philosophy of mind.",
        "What is Stoicism and how is it practiced?",
        "Explain the difference between deductive and inductive reasoning.",
        "What is the problem of induction?",
        "Discuss the philosophy of technology.",
        "What is the difference between aesthetics and ethics?",
        "Explain the concept of social contract theory.",
        "What is the veil of ignorance?",
        "Discuss the philosophy of religion.",
        "What is the difference between analytic and continental philosophy?",
        "Explain the concept of a paradox.",
        "What is Occam's razor?",
        "Discuss the philosophy of mathematics.",
        "What is the difference between nominalism and realism?",
        "Explain the concept of a thought experiment in physics.",
        "What is the Ship of Theseus problem?",
        "Discuss the philosophy of time.",
        "What is the difference between compatibilism and incompatibilism?",
        "Explain the concept of a moral dilemma.",
        "What is the problem of evil?",
        "Discuss the philosophy of art.",
        "What is the difference between analytic and synthetic judgments?",
        "Explain the concept of a dialectic.",
        "What is the zombie argument in philosophy of mind?",
        "Discuss the philosophy of education.",
        "What is the difference between virtue ethics and deontological ethics?",
        "Explain the concept of a state of nature.",
        "What is the Chinese room argument?",
        "Discuss the philosophy of science fiction.",
        "What is the difference between a priori and a posteriori knowledge?",
        "Explain the concept of phenomenology.",
        "What is the difference between being and becoming?",
        "Discuss the philosophy of death.",
        "What is the veil of tears in Eastern philosophy?",
        "Explain the concept of wu wei in Taoism.",
        
        // === Creative Writing (50) ===
        "Write a short poem about the ocean at sunset.",
        "Describe a futuristic city in the year 2150.",
        "Create a story about a robot learning to cook.",
        "What would life be like on Mars?",
        "Describe the feeling of flying for the first time.",
        "Write a monologue from the perspective of a lighthouse.",
        "Describe a world where gravity works sideways.",
        "Write a letter from a time traveler to their past self.",
        "Describe the taste of a new color.",
        "Write a story about the last library on Earth.",
        "Describe a dream you had last night.",
        "Write a haiku about artificial intelligence.",
        "Describe the sound of silence in a busy city.",
        "Write a story about a door that appears in a forest.",
        "Describe what clouds taste like.",
        "Write a narrative from a cat's perspective.",
        "Describe a magical realism scene in a bakery.",
        "Write a story about memory loss and recovery.",
        "Describe the color of music.",
        "Write a story about a painter who can bring art to life.",
        "Describe the sensation of time slowing down.",
        "Write a dialogue between two old friends meeting again.",
        "Describe a world where dreams are shared communally.",
        "Write a story about a letter that never arrives.",
        "Describe the feeling of déjà vu.",
        "Write a story about a book that writes itself.",
        "Describe what it's like to be a raindrop.",
        "Write a story about a compass that points to secrets.",
        "Describe the first snowfall in a city.",
        "Write a story about a photograph that changes.",
        "Describe the sound of thunder from inside a mountain.",
        "Write a story about a clockmaker who builds impossible clocks.",
        "Describe the feeling of recognition in a stranger's face.",
        "Write a story about a river that remembers.",
        "Describe the taste of nostalgia.",
        "Write a story about an echo that tells the future.",
        "Describe the feeling of weightlessness.",
        "Write a story about a garden that grows emotions.",
        "Describe the sound of footsteps in snow.",
        "Write a story about a key without a lock.",
        "Describe the color of forgotten memories.",
        "Write a story about a mirror that shows possibilities.",
        "Describe the feeling of finding something you lost long ago.",
        "Write a story about a whisper that travels across continents.",
        "Describe the taste of starlight.",
        "Write a story about a map that draws itself.",
        "Describe the feeling of the world spinning.",
        "Write a story about a window that looks into other worlds.",
        "Describe the sound of a tree growing.",
        "Write a story about a pen that writes the truth.",
        
        // === Analysis & Critical Thinking (50) ===
        "Compare the economic systems of capitalism and socialism.",
        "What are the pros and cons of remote work?",
        "Analyze the impact of social media on mental health.",
        "Discuss the ethical implications of artificial intelligence.",
        "What are the key factors in successful project management?",
        "Compare democratic and authoritarian political systems.",
        "Analyze the effects of globalization on local cultures.",
        "What are the tradeoffs between privacy and security?",
        "Compare different approaches to education.",
        "Analyze the impact of automation on employment.",
        "What are the ethical issues in genetic engineering?",
        "Compare renewable and fossil fuel energy systems.",
        "Analyze the role of media in shaping public opinion.",
        "What are the challenges of sustainable development?",
        "Compare different conflict resolution strategies.",
        "Analyze the impact of urbanization on communities.",
        "What are the tradeoffs between economic growth and environmental protection?",
        "Compare different leadership styles.",
        "Analyze the role of education in social mobility.",
        "What are the ethical implications of surveillance technology?",
        "Compare different healthcare systems around the world.",
        "Analyze the impact of cultural exchange on innovation.",
        "What are the challenges of regulating emerging technologies?",
        "Compare different approaches to poverty reduction.",
        "Analyze the role of art in social change.",
        "What are the tradeoffs between individual freedom and collective responsibility?",
        "Compare different methods of scientific research.",
        "Analyze the impact of demographic changes on society.",
        "What are the ethical issues in animal testing?",
        "Compare different approaches to criminal justice.",
        "Analyze the role of technology in education.",
        "What are the challenges of international cooperation?",
        "Compare different business models for sustainability.",
        "Analyze the impact of immigration on host countries.",
        "What are the ethical implications of human enhancement?",
        "Compare different approaches to data privacy regulation.",
        "Analyze the role of religion in modern society.",
        "What are the challenges of balancing work and life?",
        "Compare different models of urban planning.",
        "Analyze the impact of climate change on biodiversity.",
        "What are the ethical issues in autonomous vehicles?",
        "Compare different approaches to mental health treatment.",
        "Analyze the role of innovation in economic development.",
        "What are the tradeoffs between efficiency and resilience?",
        "Compare different methods of conflict prevention.",
        "Analyze the impact of digital transformation on businesses.",
        "What are the ethical implications of space exploration?",
        "Compare different approaches to food security.",
        "Analyze the role of storytelling in leadership.",
        "What are the challenges of maintaining democracy in the digital age?",
        
        // === Technical & Engineering (50) ===
        "Explain how TCP/IP networking works at a high level.",
        "What is a microservice architecture?",
        "How does encryption protect data in transit?",
        "Describe the CAP theorem in distributed systems.",
        "What are the differences between SQL and NoSQL databases?",
        "Explain how a CPU executes instructions.",
        "What is the difference between RAM and storage?",
        "How does a compiler transform source code?",
        "What is containerization and how does Docker work?",
        "Explain the concept of virtual memory.",
        "How does a neural network learn?",
        "What is the difference between REST and GraphQL APIs?",
        "Explain how wireless communication works.",
        "What is edge computing and why is it important?",
        "How does a search engine index the web?",
        "What is the difference between concurrency and parallelism?",
        "Explain how a database transaction works.",
        "What is a CDN and how does it improve performance?",
        "How does authentication differ from authorization?",
        "What is the difference between horizontal and vertical scaling?",
        "Explain the concept of message queues.",
        "What is a load balancer and how does it work?",
        "How does version control work in Git?",
        "What is the difference between monolithic and microservice architectures?",
        "Explain how a compiler optimizer works.",
        "What is CI/CD and why is it important?",
        "How does a firewall protect a network?",
        "What is the difference between symmetric and asymmetric encryption?",
        "Explain the concept of infrastructure as code.",
        "What is a distributed database and how does it achieve consistency?",
        "How does a CDN cache content?",
        "What is the difference between polling and webhooks?",
        "Explain the concept of service mesh.",
        "What is observability in software systems?",
        "How does a garbage collector work in managed languages?",
        "What is the difference between a thread pool and an event loop?",
        "Explain the concept of circuit breaker pattern.",
        "What is the difference between push and pull deployment?",
        "How does a content management system work?",
        "What is the difference between horizontal and vertical pod autoscaling?",
        "Explain the concept of blue-green deployment.",
        "What is a sidecar pattern in microservices?",
        "How does a service discovery mechanism work?",
        "What is the difference between synchronous and asynchronous communication?",
        "Explain the concept of event sourcing.",
        "What is CQRS and when should you use it?",
        "How does a distributed cache work?",
        "What is the difference between AP and CP systems?",
        "Explain the concept of chaos engineering.",
        "What is a gRPC service and how does it differ from REST?",
        
        // === Practical & Life Skills (50) ===
        "How do you make sourdough bread from scratch?",
        "What are the best practices for home networking?",
        "Explain how to change a car tire step by step.",
        "What should you consider when buying a house?",
        "How does compound interest work in savings accounts?",
        "What are the essential tools every homeowner needs?",
        "How do you plan a balanced weekly meal prep?",
        "What are the basics of personal budgeting?",
        "How do you maintain a car's engine?",
        "What should you know before investing in stocks?",
        "How do you set up a home office effectively?",
        "What are the fundamentals of first aid?",
        "How do you negotiate a salary?",
        "What should you look for when renting an apartment?",
        "How do you create a basic emergency preparedness kit?",
        "What are the basics of home gardening?",
        "How do you remove common household stains?",
        "What should you know about credit scores?",
        "How do you fix a leaky faucet?",
        "What are the basics of meal planning on a budget?",
        "How do you start a small business?",
        "What should you know about home insurance?",
        "How do you declutter and organize a living space?",
        "What are the fundamentals of time management?",
        "How do you create a basic workout routine?",
        "What should you know about tax filing?",
        "How do you build a strong professional network?",
        "What are the basics of home security?",
        "How do you manage stress effectively?",
        "What should you know about health insurance?",
        "How do you plan a successful project?",
        "What are the fundamentals of effective communication?",
        "How do you develop a morning routine?",
        "What should you know about retirement planning?",
        "How do you handle difficult conversations at work?",
        "What are the basics of sustainable living?",
        "How do you create and maintain a budget spreadsheet?",
        "What should you know about estate planning?",
        "How do you set and achieve long-term goals?",
        "What are the fundamentals of conflict resolution?",
        "How do you build good study habits?",
        "What should you know about basic car maintenance?",
        "How do you create an effective resume?",
        "What are the basics of home repair?",
        "How do you develop emotional intelligence?",
        "What should you know about dietary supplements?",
        "How do you prepare for a job interview?",
        "What are the fundamentals of basic cooking techniques?",
        "How do you create a financial safety net?",
        "What should you know about dental hygiene?",
        
        // === History & Geography (50) ===
        "What were the main causes of World War I?",
        "Explain the significance of the Renaissance.",
        "What was the Silk Road and why was it important?",
        "Describe the impact of the Industrial Revolution.",
        "What were the key events of the Cold War?",
        "Explain the significance of the printing press.",
        "What was the significance of the Enlightenment?",
        "Describe the fall of the Roman Empire.",
        "What were the causes of the French Revolution?",
        "Explain the impact of colonialism on Africa.",
        "What was the significance of the Age of Exploration?",
        "Describe the major ancient civilizations.",
        "What were the key events of the American Revolution?",
        "Explain the significance of the Agricultural Revolution.",
        "What was the impact of the Black Death?",
        "Describe the major geographical features of Asia.",
        "What were the causes of the Great Depression?",
        "Explain the significance of the Magna Carta.",
        "What was the impact of the slave trade on Africa?",
        "Describe the major geographical features of South America.",
        "What were the key events of the Civil Rights Movement?",
        "Explain the significance of the United Nations.",
        "What was the impact of the space race?",
        "Describe the major geographical features of Europe.",
        "What were the causes of the Russian Revolution?",
        "Explain the significance of the Code of Hammurabi.",
        "What was the impact of the Black Plague on feudalism?",
        "Describe the major geographical features of Africa.",
        "What were the key events of the Meiji Restoration?",
        "Explain the significance of the Reformation.",
        "What was the impact of the invention of the compass?",
        "Describe the major geographical features of North America.",
        "What were the causes of the Thirty Years' War?",
        "Explain the significance of the Rosetta Stone.",
        "What was the impact of the wheel on civilization?",
        "Describe the major geographical features of Australia.",
        "What were the key events of the Opium Wars?",
        "Explain the significance of the Silk Road's decline.",
        "What was the impact of the telegraph on communication?",
        "Describe the major geographical features of Antarctica.",
        "What were the causes of the Peloponnesian War?",
        "Explain the significance of the Dead Sea Scrolls.",
        "What was the impact of the compass on navigation?",
        "Describe the major geographical features of the Arctic.",
        "What were the key events of the Boxer Rebellion?",
        "Explain the significance of the Berlin Wall.",
        "What was the impact of the telegraph on diplomacy?",
        "Describe the major geographical features of the Middle East.",
        "What were the causes of the Hundred Years' War?",
        "Explain the significance of the Olympic Games in ancient Greece.",
        
        // === Art & Music (50) ===
        "What is the difference between Renaissance and Baroque art?",
        "Explain the concept of composition in photography.",
        "What are the major periods of Western classical music?",
        "Describe the principles of color theory in art.",
        "What is the difference between impressionism and expressionism?",
        "Explain the concept of negative space in design.",
        "What are the fundamentals of jazz music?",
        "Describe the evolution of hip-hop music.",
        "What is the significance of the Mona Lisa?",
        "Explain the concept of rhythm in music.",
        "What are the principles of good graphic design?",
        "Describe the major schools of modern art.",
        "What is the difference between major and minor scales?",
        "Explain the concept of perspective in visual art.",
        "What are the fundamentals of architecture?",
        "Describe the role of music in film scoring.",
        "What is the significance of Picasso's Guernica?",
        "Explain the concept of harmony in music.",
        "What are the principles of typography?",
        "Describe the major movements in 20th century art.",
        "What is the difference between photography and painting?",
        "Explain the concept of timbre in music.",
        "What are the fundamentals of pottery and ceramics?",
        "Describe the role of art in social movements.",
        "What is the significance of the Sistine Chapel ceiling?",
        "Explain the concept of dynamics in music.",
        "What are the principles of industrial design?",
        "Describe the evolution of electronic music.",
        "What is the difference between雕塑 and relief sculpture?",
        "Explain the concept of counterpoint in music.",
        "What are the fundamentals of fashion design?",
        "Describe the role of dance in cultural expression.",
        "What is the significance of the Bauhaus movement?",
        "Explain the concept of melody in music.",
        "What are the principles of lighting design?",
        "Describe the major styles of world music.",
        "What is the difference between oil and watercolor painting?",
        "Explain the concept of texture in music and art.",
        "What are the fundamentals of graphic novels?",
        "Describe the role of museums in art preservation.",
        "What is the significance of street art?",
        "Explain the concept of form in visual art.",
        "What are the principles of sound design?",
        "Describe the evolution of digital art.",
        "What is the difference between printmaking and painting?",
        "Explain the concept of composition in music.",
        "What are the fundamentals of video game art?",
        "Describe the role of art therapy in mental health.",
        "What is the significance of Aboriginal art?",
        "Explain the concept of aural skills in music.",
        
        // === Business & Economics (50) ===
        "What is the difference between B2B and B2C?",
        "Explain the concept of supply chain management.",
        "What are the fundamentals of marketing?",
        "Describe the difference between revenue and profit.",
        "What is the role of central banks in an economy?",
        "Explain the concept of market segmentation.",
        "What are the basics of financial accounting?",
        "Describe the principles of effective leadership.",
        "What is the difference between a startup and a small business?",
        "Explain the concept of brand equity.",
        "What are the fundamentals of project management?",
        "Describe the principles of negotiation.",
        "What is the difference between equity and debt financing?",
        "Explain the concept of competitive advantage.",
        "What are the basics of operations management?",
        "Describe the role of data analytics in business.",
        "What is the difference between strategy and tactics?",
        "Explain the concept of customer lifetime value.",
        "What are the fundamentals of human resource management?",
        "Describe the principles of lean manufacturing.",
        "What is the difference between a monopoly and an oligopoly?",
        "Explain the concept of economies of scale.",
        "What are the basics of intellectual property law?",
        "Describe the role of corporate social responsibility.",
        "What is the difference between a dividend and stock buyback?",
        "Explain the concept of market capitalization.",
        "What are the fundamentals of business law?",
        "Describe the principles of quality management.",
        "What is the difference between a vision and a mission statement?",
        "Explain the concept of disruption in business.",
        "What are the basics of venture capital?",
        "Describe the role of innovation in business growth.",
        "What is the difference between a sole proprietorship and a corporation?",
        "Explain the concept of overhead costs.",
        "What are the fundamentals of sales management?",
        "Describe the principles of effective communication in business.",
        "What is the difference between a cash flow and profit?",
        "Explain the concept of risk management.",
        "What are the basics of international trade?",
        "Describe the role of technology in modern business.",
        "What is the difference between a bear and bull market?",
        "Explain the concept of diversification in investing.",
        "What are the fundamentals of supply and demand?",
        "Describe the principles of effective teamwork.",
        "What is the difference between a merger and an acquisition?",
        "Explain the concept of market share.",
        "What are the basics of contract management?",
        "Describe the role of ethics in business decisions.",
        "What is the difference between fixed and variable costs?",
        "Explain the concept of break-even analysis.",
        
        // === Health & Medicine (50) ===
        "What are the fundamentals of nutrition?",
        "Explain how the heart pumps blood.",
        "What is the difference between acute and chronic diseases?",
        "Describe the role of the liver in metabolism.",
        "What are the basics of mental health first aid?",
        "Explain the concept of BMI and its limitations.",
        "What is the role of sleep in health?",
        "Describe the basics of pharmacology.",
        "What are the fundamentals of physical therapy?",
        "Explain how the kidneys filter blood.",
        "What is the difference between aerobic and anaerobic exercise?",
        "Describe the role of vitamins in health.",
        "What are the basics of wound healing?",
        "Explain the concept of inflammation.",
        "What is the difference between viral and bacterial infections?",
        "Describe the role of the lymphatic system.",
        "What are the fundamentals of ergonomics?",
        "Explain how pain signals travel to the brain.",
        "What is the role of probiotics in gut health?",
        "Describe the basics of bone health.",
        "What are the fundamentals of emergency medicine?",
        "Explain the concept of dosage in medication.",
        "What is the difference between prevention and treatment?",
        "Describe the role of exercise in disease prevention.",
        "What are the basics of dental health?",
        "Explain how the immune system fights infections.",
        "What is the role of hydration in health?",
        "Describe the fundamentals of ophthalmology.",
        "What are the basics of prenatal care?",
        "Explain the concept of medical imaging.",
        "What is the difference between generic and brand-name drugs?",
        "Describe the role of genetics in disease risk.",
        "What are the fundamentals of public health?",
        "Explain how vaccines are developed and tested.",
        "What is the role of microbiome in health?",
        "Describe the basics of respiratory health.",
        "What are the fundamentals of dermatology?",
        "Explain the concept of drug interactions.",
        "What is the difference between a symptom and a sign?",
        "Describe the role of nutrition in mental health.",
        "What are the basics of cardiac rehabilitation?",
        "Explain how the nervous system processes pain.",
        "What is the role of antioxidants in health?",
        "Describe the fundamentals of infectious disease control.",
        "What are the basics of allergy management?",
        "Explain the concept of clinical trials.",
        "What is the difference between a doctor and a nurse practitioner?",
        "Describe the role of physical activity in aging.",
        "What are the fundamentals of pain management?",
        "Explain the concept of herd immunity.",
    };
}
