// =============================================================================
// Vessel Web Dashboard Server
// =============================================================================
// Phase B: cpp-httplib integration with embedded web assets
// Serves the dashboard on http://localhost:8080
// =============================================================================

#include "web_server.h"
#include "types.h"
#include "profiler.h"
#include "../predictor/predictor.h"
#include "matrix.h"
#include "ranker.h"
#include "output.h"
#include "fetcher.h"
#include "calibration_log.h"
#include "calibration_aggregator.h"
#include "recommend/catalog_loader.h"
#include "recommend/recommendation_engine.h"
#include "platform/platform_factory.h"

#include <cstdio>
#include <string>
#include <mutex>
#include <atomic>
#include <thread>
#include <chrono>

// Timer utility (same as main.cpp)
class Timer {
    std::chrono::high_resolution_clock::time_point t0;
public:
    Timer() : t0(std::chrono::high_resolution_clock::now()) {}
    double elapsed_ms() {
        auto now = std::chrono::high_resolution_clock::now();
        return std::chrono::duration<double, std::milli>(now - t0).count();
    }
};

// Explicitly disable SSL - we only need plain HTTP for localhost
#define CPPHTTPLIB_NO_OPENSSL
#ifdef CPPHTTPLIB_OPENSSL_SUPPORT
#undef CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include "httplib.h"

#include <nlohmann/json.hpp>

#ifdef _WIN32
#include <windows.h>
#include <shellapi.h>
#endif

using json = nlohmann::json;

// =============================================================================
// Embedded web assets (generated by CMake at build time)
// =============================================================================
// If embedded_web.h doesn't exist, the build will fail with a clear error.
// The CMake embed_files function generates this from web/index.html, web/app.js, web/styles.css
#include "embedded_web.h"

// =============================================================================
// Global state
// =============================================================================
static std::mutex g_task_mutex;
static std::atomic<bool> g_task_running{false};

// =============================================================================
// Cross-platform browser opener
// =============================================================================
static void openBrowser(const std::string& url) {
#ifdef _WIN32
    ShellExecuteA(NULL, "open", url.c_str(), NULL, NULL, SW_SHOWNORMAL);
#elif __APPLE__
    std::system(("open " + url).c_str());
#else
    std::system(("xdg-open " + url + " &").c_str());
#endif
}

// =============================================================================
// JSON helpers
// =============================================================================
static json hardwareToJson(const HardwareSpec& hw) {
    json j;
    j["gpu_name"] = hw.gpu_name;
    j["vram_total"] = hw.vram_total_bytes;
    j["vram_used"] = hw.vram_total_bytes - hw.vram_free_bytes;
    j["vram_free"] = hw.vram_free_bytes;
    j["ram_total"] = hw.ram_total_bytes;
    j["ram_used"] = hw.ram_total_bytes - hw.ram_free_bytes;
    j["ram_free"] = hw.ram_free_bytes;
    j["temp"] = hw.gpu_temp_celsius;
    j["gpu_bw"] = hw.gpu_bandwidth_gbs;
    j["gpu_tflops"] = hw.gpu_tflops_fp16;
    j["ram_bw"] = hw.ram_bandwidth_gbs;
    j["nvme_seq"] = hw.nvme_sequential_mbs;
    j["nvme_rand"] = hw.nvme_random_4k_mbs;
    j["platform"] = hw.gpu_name.empty() ? "CPU" : hw.gpu_name;
    j["fingerprint"] = hw.hardware_fingerprint;
    j["unified_memory"] = hw.is_unified_memory;
    return j;
}

static json predictionToJson(const Prediction& p, const StrategyConfig& s) {
    json j;
    j["vram"] = p.memory_vram_bytes;
    j["ram"] = p.memory_ram_bytes;
    j["tps"] = p.tokens_per_sec;
    j["ttft"] = p.ttft_ms;
    j["viable"] = p.viable;
    j["confidence"] = (p.confidence == PredictionConfidence::HIGH) ? "HIGH" :
                      (p.confidence == PredictionConfidence::MEDIUM) ? "MEDIUM" : "LOW";

    // Placement
    switch (s.placement) {
        case PlacementStrategy::FULL_GPU:       j["placement"] = "FULL_GPU"; break;
        case PlacementStrategy::GPU_CPU_SPLIT:  j["placement"] = "GPU_CPU_SPLIT"; break;
        case PlacementStrategy::CPU_ONLY:       j["placement"] = "CPU_ONLY"; break;
        case PlacementStrategy::HOT_COLD_SPLIT: j["placement"] = "HOT_COLD_SPLIT"; break;
        case PlacementStrategy::LAYER_STREAM:   j["placement"] = "LAYER_STREAM"; break;
        default:                               j["placement"] = "UNKNOWN"; break;
    }
    j["gpu_layers"] = s.gpu_layers;
    j["ctx"] = s.context_length;
    j["kv"] = s.kv_quant_bits;

    // MoE range
    if (p.is_moe_range) {
        j["tps_best"] = p.tok_s_best;
        j["tps_worst"] = p.tok_s_worst;
        j["tps_expected"] = p.tok_s_expected;
    }
    return j;
}

static std::string starsString(double score) {
    int full = (int)(score / 2.0 + 0.5);
    if (full > 5) full = 5;
    if (full < 0) full = 0;
    std::string s;
    for (int i = 0; i < full; i++) s += "\xe2\x98\x85";  // ★
    for (int i = full; i < 5; i++) s += "\xe2\x98\x86";  // ☆
    return s;
}

// =============================================================================
// API Route Handlers
// =============================================================================

// GET /api/hardware - Profile hardware and return JSON
static void handleHardware(const httplib::Request& req, httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");

    // Use a temporary model path for fingerprint (empty is fine)
    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);
    json j = hardwareToJson(hw);
    res.set_content(j.dump(), "application/json");
}

// POST /api/predict - Fetch metadata and predict strategies
static void handlePredict(const httplib::Request& req, httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");

    json body;
    try {
        body = json::parse(req.body);
    } catch (...) {
        res.status = 400;
        res.set_content(R"({"error":"Invalid JSON"})", "application/json");
        return;
    }

    std::string model_url = body.value("model_url", "");
    if (model_url.empty()) {
        res.status = 400;
        res.set_content(R"({"error":"model_url required"})", "application/json");
        return;
    }

    // Profile hardware
    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    // Fetch metadata
    Timer t_meta;
    ModelSpec model = fetch_metadata(model_url);
    double meta_ms = t_meta.elapsed_ms();

    if (model.layers == 0) {
        res.status = 404;
        json err;
        err["error"] = "Failed to fetch model metadata";
        err["details"] = get_fetch_error();
        err["http_status"] = get_fetch_http_status();
        res.set_content(err.dump(), "application/json");
        return;
    }

    // Load calibration
    CalibrationAggregator cal_agg(hw.hardware_fingerprint);
    CalibrationData cal = cal_agg.get_calibration_data();

    // Generate matrix
    Timer t_matrix;
    std::vector<StrategyResult> results = generate_matrix(hw, model, cal);
    double matrix_ms = t_matrix.elapsed_ms();

    // Sort by speed
    sort_by_priority(results, PriorityMode::SPEED, hw);

    // Build response
    json response;
    response["model"]["name"] = model.name;
    response["model"]["params"] = model.param_count;
    response["model"]["layers"] = model.layers;
    response["model"]["arch"] = model.architecture;
    response["model"]["is_moe"] = model.is_moe;
    response["model"]["quant"] = model.quant_type;
    response["model"]["context"] = model.context_length;
    response["hw"] = hardwareToJson(hw);
    response["time_ms"] = (int)(meta_ms + matrix_ms);

    json strategies = json::array();
    for (const auto& r : results) {
        json sj = predictionToJson(r.prediction, r.strategy);
        // Add status
        StrategyStatus st = determine_status(hw, r.prediction, r.strategy);
        switch (st) {
            case StrategyStatus::VIABLE:    sj["status"] = "VIABLE"; break;
            case StrategyStatus::TIGHT:     sj["status"] = "TIGHT"; break;
            case StrategyStatus::NO_FIT:    sj["status"] = "NO_FIT"; break;
            case StrategyStatus::LOW_CONF:  sj["status"] = "LOW_CONF"; break;
            default:                        sj["status"] = "UNKNOWN"; break;
        }
        strategies.push_back(sj);
    }
    response["strategies"] = strategies;

    res.set_content(response.dump(), "application/json");
}

// GET /api/recommend - Model recommendations
static void handleRecommend(const httplib::Request& req, httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");

    std::string priority = req.get_param_value("priority").empty() ? "balanced" : req.get_param_value("priority");
    std::string use_case = req.get_param_value("use_case").empty() ? "all" : req.get_param_value("use_case");
    int top_n = 8;
    try { top_n = std::stoi(req.get_param_value("top")); } catch (...) {}

    // Profile hardware
    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    // Load catalog
    ModelCatalog catalog = load_builtin_catalog();

    // Generate recommendations
    RecommendationRequest req2;
    req2.priority = priority;
    req2.use_case = use_case;
    req2.top_n = top_n;

    auto recs = generate_recommendations(hw, catalog, req2);

    json response;
    json recs_json = json::array();
    std::string top_pick;

    for (size_t i = 0; i < recs.size(); i++) {
        const auto& r = recs[i];
        json rj;
        rj["model"] = r.model.name;
        rj["quant"] = r.variant.quant;
        rj["strategy"] = r.best_strategy_desc;
        rj["vram"] = (uint64_t)(r.predicted_vram_gb * 1e9);
        rj["tps"] = r.predicted_tok_s;
        rj["quality"] = r.model.quality_score;
        rj["quality_stars"] = starsString(r.model.quality_score);
        rj["download_gb"] = r.variant.file_size_gb;
        rj["url"] = r.variant.hf_url;
        rj["label"] = r.label;
        recs_json.push_back(rj);

        if (i == 0) {
            top_pick = r.model.name + " " + r.variant.quant + " - " + r.label;
        }
    }

    response["recommendations"] = recs_json;
    response["top_pick"] = top_pick;
    response["count"] = recs.size();

    res.set_content(response.dump(), "application/json");
}

// GET /api/calibration - Calibration info
static void handleCalibration(const httplib::Request& req, httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");

    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    std::string log_path = get_log_path();
    auto records = read_all_records(log_path);

    json response;
    response["records"] = records.size();
    response["fingerprint"] = hw.hardware_fingerprint;
    response["log_path"] = log_path;

    // Matching records
    int match_count = 0;
    for (const auto& r : records) {
        if (r.hardware_fingerprint == hw.hardware_fingerprint) match_count++;
    }
    response["matching_records"] = match_count;

    if (match_count > 0) {
        CalibrationAggregator agg(hw.hardware_fingerprint);
        CalibrationData cal = agg.get_calibration_data();
        response["gpu_overhead_mb"] = cal.adjusted_gpu_overhead_bytes / (1024 * 1024);
        response["gpu_decode_eff"] = cal.adjusted_gpu_decode_efficiency > 0 ? cal.adjusted_gpu_decode_efficiency : 0.27;
        response["cpu_decode_eff"] = cal.adjusted_cpu_decode_efficiency > 0 ? cal.adjusted_cpu_decode_efficiency : 0.80;
        response["gpu_prefill_eff"] = cal.adjusted_gpu_prefill_efficiency > 0 ? cal.adjusted_gpu_prefill_efficiency : 0.23;
    }

    res.set_content(response.dump(), "application/json");
}

// =============================================================================
// Static File Routes
// =============================================================================
static void setupStaticRoutes(httplib::Server& server) {
    server.Get("/", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_INDEX_HTML, WEB_INDEX_HTML_MIME);
    });
    server.Get("/app.js", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_APP_JS, WEB_APP_JS_MIME);
    });
    server.Get("/styles.css", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_STYLES_CSS, WEB_STYLES_CSS_MIME);
    });
}

// =============================================================================
// API Routes
// =============================================================================
static void setupApiRoutes(httplib::Server& server) {
    server.Get("/api/hardware", handleHardware);
    server.Post("/api/predict", handlePredict);
    server.Get("/api/recommend", handleRecommend);
    server.Get("/api/calibration", handleCalibration);

    // CORS preflight
    server.Options(".*", [](const httplib::Request&, httplib::Response& res) {
        res.set_header("Access-Control-Allow-Origin", "*");
        res.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
        res.set_header("Access-Control-Allow-Headers", "Content-Type");
        res.status = 204;
    });
}

// =============================================================================
// Public API
// =============================================================================
bool start_web_server(int port, const std::string& model_for_fingerprint, bool open_browser_flag) {
    httplib::Server server;

    setupStaticRoutes(server);
    setupApiRoutes(server);

    // Error handling
    server.set_error_handler([](const httplib::Request&, httplib::Response& res) {
        json err;
        err["error"] = "Not found";
        err["status"] = res.status;
        res.set_content(err.dump(), "application/json");
    });

    printf("\n");
    printf("  Vessel Dashboard\n");
    printf("  http://localhost:%d\n", port);
    printf("  Press Ctrl+C to stop\n\n", port);

    if (open_browser_flag) {
        openBrowser("http://localhost:" + std::to_string(port));
    }

    return server.listen("0.0.0.0", port);
}
