// =============================================================================
// Vessel Web Dashboard Server
// =============================================================================
// Phase C: Full REST API with SSE streaming for live data, downloads, execution
// =============================================================================

#include "web_server.h"
#include "types.h"
#include "profiler.h"
#include "../predictor/predictor.h"
#include "matrix.h"
#include "ranker.h"
#include "output.h"
#include "fetcher.h"
#include "download_manager.h"
#include "calibration_log.h"
#include "calibration_aggregator.h"
#include "recommend/catalog_loader.h"
#include "recommend/recommendation_engine.h"
#include "platform/platform_factory.h"

#include <cstdio>
#include <string>
#include <mutex>
#include <atomic>
#include <thread>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <regex>

// Timer utility
class Timer {
    std::chrono::high_resolution_clock::time_point t0;
public:
    Timer() : t0(std::chrono::high_resolution_clock::now()) {}
    double elapsed_ms() {
        auto now = std::chrono::high_resolution_clock::now();
        return std::chrono::duration<double, std::milli>(now - t0).count();
    }
};

// Explicitly disable SSL - we only need plain HTTP for localhost
#ifdef CPPHTTPLIB_OPENSSL_SUPPORT
#undef CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include "httplib.h"

#include <nlohmann/json.hpp>

#ifdef _WIN32
#include <windows.h>
#include <shellapi.h>
#endif

namespace fs = std::filesystem;
using json = nlohmann::json;

// =============================================================================
// Embedded web assets (generated by CMake at build time)
// =============================================================================
#include "embedded_web.h"

// =============================================================================
// JSON Response Envelope
// =============================================================================
static json makeSuccess(const json& data) {
    json j;
    j["success"] = true;
    j["data"] = data;
    j["error"] = nullptr;
    return j;
}

static json makeError(const std::string& code, const std::string& message, const std::string& details = "") {
    json j;
    j["success"] = false;
    j["data"] = nullptr;
    j["error"] = { {"code", code}, {"message", message}, {"details", details} };
    return j;
}

static void sendJson(httplib::Response& res, int status, const json& envelope) {
    res.status = status;
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_header("Content-Type", "application/json");
    res.set_content(envelope.dump(), "application/json");
}

static void sendSSEHeader(httplib::Response& res) {
    res.set_header("Access-Control-Allow-Origin", "*");
    res.set_header("Content-Type", "text/event-stream");
    res.set_header("Cache-Control", "no-cache");
    res.set_header("Connection", "keep-alive");
}

// =============================================================================
// Global state
// =============================================================================
static std::mutex g_task_mutex;
static std::atomic<bool> g_task_running{false};
static std::string g_active_task_type;  // "download" or "execute"
static std::string g_active_task_id;

// Task ID generator
static std::string generateTaskId(const std::string& prefix) {
    static std::atomic<int> counter{0};
    auto now = std::chrono::system_clock::now().time_since_epoch().count();
    int id = counter.fetch_add(1);
    char buf[32];
    snprintf(buf, sizeof(buf), "%s_%x_%d", prefix.c_str(), (unsigned)(now & 0xFFFF), id);
    return std::string(buf);
}

// Cross-platform browser opener
static void openBrowser(const std::string& url) {
#ifdef _WIN32
    ShellExecuteA(NULL, "open", url.c_str(), NULL, NULL, SW_SHOWNORMAL);
#elif __APPLE__
    std::system(("open " + url).c_str());
#else
    std::system(("xdg-open " + url + " &").c_str());
#endif
}

// =============================================================================
// JSON Conversion Helpers
// =============================================================================
static json hardwareToJson(const HardwareSpec& hw) {
    json j;
    j["platform"] = hw.gpu_name.empty() ? "cpu" : (hw.is_nvidia() ? "nvidia" : hw.is_amd() ? "amd" : hw.is_apple() ? "apple" : "unknown");
    j["gpu_name"] = hw.gpu_name;
    j["vram_total_bytes"] = hw.vram_total_bytes;
    j["vram_free_bytes"] = hw.vram_free_bytes;
    j["vram_used_pct"] = hw.vram_total_bytes > 0 ? 100.0 * (hw.vram_total_bytes - hw.vram_free_bytes) / hw.vram_total_bytes : 0.0;
    j["ram_total_bytes"] = hw.ram_total_bytes;
    j["ram_free_bytes"] = hw.ram_free_bytes;
    j["ram_used_pct"] = hw.ram_total_bytes > 0 ? 100.0 * (hw.ram_total_bytes - hw.ram_free_bytes) / hw.ram_total_bytes : 0.0;
    j["gpu_bandwidth_gbs"] = hw.gpu_bandwidth_gbs;
    j["gpu_tflops_fp16"] = hw.gpu_tflops_fp16;
    j["ram_bandwidth_gbs"] = hw.ram_bandwidth_gbs;
    j["nvme_sequential_mbs"] = hw.nvme_sequential_mbs;
    j["nvme_random_4k_mbs"] = hw.nvme_random_4k_mbs;
    j["gpu_temp_celsius"] = hw.gpu_temp_celsius;
    j["gpu_clock_mhz"] = hw.gpu_clock_mhz;
    j["hardware_fingerprint"] = hw.hardware_fingerprint;
    j["is_unified_memory"] = hw.is_unified_memory;
    return j;
}

static json hardwareToLiveJson(const HardwareSpec& hw) {
    json j;
    j["vram_free_bytes"] = hw.vram_free_bytes;
    j["vram_used_bytes"] = hw.vram_total_bytes - hw.vram_free_bytes;
    j["ram_free_bytes"] = hw.ram_free_bytes;
    j["gpu_temp_celsius"] = hw.gpu_temp_celsius;
    j["gpu_clock_mhz"] = hw.gpu_clock_mhz;
    j["gpu_utilization"] = hw.gpu_utilization;
    return j;
}

static json predictionToJson(const Prediction& p, const StrategyConfig& s, int rank = 0) {
    json j;
    j["rank"] = rank;
    j["vram_bytes"] = p.memory_vram_bytes;
    j["ram_bytes"] = p.memory_ram_bytes;
    j["tokens_per_sec"] = p.tokens_per_sec;
    j["ttft_ms"] = p.ttft_ms;
    j["viable"] = p.viable;

    switch (p.confidence) {
        case PredictionConfidence::HIGH:   j["confidence"] = "HIGH"; break;
        case PredictionConfidence::MEDIUM: j["confidence"] = "MEDIUM"; break;
        default:                           j["confidence"] = "LOW"; break;
    }

    switch (s.placement) {
        case PlacementStrategy::FULL_GPU:       j["placement"] = "FULL_GPU"; break;
        case PlacementStrategy::GPU_CPU_SPLIT:  j["placement"] = "GPU_CPU_SPLIT"; break;
        case PlacementStrategy::CPU_ONLY:       j["placement"] = "CPU_ONLY"; break;
        case PlacementStrategy::HOT_COLD_SPLIT: j["placement"] = "HOT_COLD_SPLIT"; break;
        case PlacementStrategy::LAYER_STREAM:   j["placement"] = "LAYER_STREAM"; break;
        default:                               j["placement"] = "UNKNOWN"; break;
    }
    j["gpu_layers"] = s.gpu_layers;
    j["context_length"] = s.context_length;
    j["kv_quant_bits"] = s.kv_quant_bits;
    return j;
}

static std::string starsString(double score) {
    int full = (int)(score / 2.0 + 0.5);
    if (full > 5) full = 5;
    if (full < 0) full = 0;
    std::string s;
    for (int i = 0; i < full; i++) s += "\xe2\x98\x85";  // star
    for (int i = full; i < 5; i++) s += "\xe2\x98\x86";  // empty star
    return s;
}

static std::string currentTimestamp() {
    auto now = std::chrono::system_clock::now();
    auto t = std::chrono::system_clock::to_time_t(now);
    char buf[64];
    struct tm tm_buf;
#ifdef _WIN32
    gmtime_s(&tm_buf, &t);
#else
    gmtime_r(&t, &tm_buf);
#endif
    strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", &tm_buf);
    return std::string(buf);
}

// =============================================================================
// API Route Handlers
// =============================================================================

// GET /api/health
static void handleHealth(const httplib::Request&, httplib::Response& res) {
    sendJson(res, 200, makeSuccess({ {"status", "ok"}, {"version", "0.1.0"} }));
}

// GET /api/hardware
static void handleHardware(const httplib::Request&, httplib::Response& res) {
    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);
    json data = hardwareToJson(hw);
    data["profiled_at"] = currentTimestamp();
    sendJson(res, 200, makeSuccess(data));
}

// GET /api/hardware/live (SSE)
static void handleHardwareLive(const httplib::Request&, httplib::Response& res) {
    sendSSEHeader(res);

    res.set_chunked_content_provider("text/event-stream",
        [](size_t, httplib::DataSink& sink) -> bool {
            static std::string model_for_fp;
            static auto last_send = std::chrono::steady_clock::now();

            auto now = std::chrono::steady_clock::now();
            auto elapsed_ms = std::chrono::duration_cast<std::chrono::milliseconds>(now - last_send).count();

            if (elapsed_ms < 500) {
                std::this_thread::sleep_for(std::chrono::milliseconds(200));
                return true;  // Keep streaming
            }

            HardwareSpec hw = profile_hardware(model_for_fp);
            json data = hardwareToLiveJson(hw);

            std::string sse_data = "event: hardware\ndata: " + data.dump() + "\n\n";
            bool ok = sink.write(sse_data.c_str(), sse_data.size());
            last_send = now;
            return ok;  // false = client disconnected
        });
}

// POST /api/predict
static void handlePredict(const httplib::Request& req, httplib::Response& res) {
    json body;
    try {
        body = json::parse(req.body);
    } catch (...) {
        sendJson(res, 400, makeError("INVALID_JSON", "Request body is not valid JSON"));
        return;
    }

    std::string model_url = body.value("model_url", "");
    if (model_url.empty()) {
        sendJson(res, 400, makeError("MISSING_PARAM", "model_url is required"));
        return;
    }

    std::string priority = body.value("priority", "speed");

    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    Timer t_meta;
    ModelSpec model = fetch_metadata(model_url);
    double meta_ms = t_meta.elapsed_ms();

    if (model.layers == 0) {
        sendJson(res, 404, makeError("MODEL_NOT_FOUND", "Failed to fetch model metadata",
            get_fetch_error()));
        return;
    }

    CalibrationAggregator cal_agg(hw.hardware_fingerprint);
    CalibrationData cal = cal_agg.get_calibration_data();

    Timer t_matrix;
    std::vector<StrategyResult> results = generate_matrix(hw, model, cal);
    double matrix_ms = t_matrix.elapsed_ms();

    PriorityMode pm = (priority == "quality") ? PriorityMode::QUALITY :
                      (priority == "safety") ? PriorityMode::SAFETY : PriorityMode::SPEED;
    sort_by_priority(results, pm, hw);

    json strategies = json::array();
    for (size_t i = 0; i < results.size(); i++) {
        json sj = predictionToJson(results[i].prediction, results[i].strategy, (int)i + 1);
        StrategyStatus st = determine_status(hw, results[i].prediction, results[i].strategy);
        switch (st) {
            case StrategyStatus::VIABLE:    sj["status"] = "VIABLE"; break;
            case StrategyStatus::TIGHT:     sj["status"] = "TIGHT"; break;
            case StrategyStatus::NO_FIT:    sj["status"] = "NO_FIT"; break;
            case StrategyStatus::LOW_CONF:  sj["status"] = "LOW_CONF"; break;
            default:                        sj["status"] = "UNKNOWN"; break;
        }
        sj["warnings"] = results[i].prediction.warnings;
        strategies.push_back(sj);
    }

    json data;
    data["model"]["name"] = model.name;
    data["model"]["params"] = model.param_count;
    data["model"]["layers"] = model.layers;
    data["model"]["architecture"] = model.architecture;
    data["model"]["is_moe"] = model.is_moe;
    data["model"]["quant"] = model.quant_type;
    data["model"]["context"] = model.context_length;
    data["hardware"] = hardwareToJson(hw);
    data["strategies"] = strategies;
    data["time_ms"] = (int)(meta_ms + matrix_ms);

    sendJson(res, 200, makeSuccess(data));
}

// GET /api/recommend
static void handleRecommend(const httplib::Request& req, httplib::Response& res) {
    std::string priority = req.get_param_value("priority").empty() ? "balanced" : req.get_param_value("priority");
    std::string use_case = req.get_param_value("use_case").empty() ? "all" : req.get_param_value("use_case");
    int top_n = 8;
    try { top_n = std::stoi(req.get_param_value("top")); } catch (...) {}

    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    ModelCatalog catalog = load_builtin_catalog();

    RecommendationRequest req2;
    req2.priority = priority;
    req2.use_case = use_case;
    req2.top_n = top_n;

    auto recs = generate_recommendations(hw, catalog, req2);

    json recs_json = json::array();
    for (size_t i = 0; i < recs.size(); i++) {
        const auto& r = recs[i];
        json rj;
        rj["model"] = r.model.name;
        rj["quant"] = r.variant.quant;
        rj["strategy"] = r.best_strategy_desc;
        rj["vram_bytes"] = (uint64_t)(r.predicted_vram_gb * 1e9);
        rj["tokens_per_sec"] = r.predicted_tok_s;
        rj["quality_score"] = r.model.quality_score;
        rj["quality_stars"] = starsString(r.model.quality_score);
        rj["download_gb"] = r.variant.file_size_gb;
        rj["hf_url"] = r.variant.hf_url;
        rj["label"] = r.label;
        recs_json.push_back(rj);
    }

    json data;
    data["recommendations"] = recs_json;
    data["count"] = recs.size();

    sendJson(res, 200, makeSuccess(data));
}

// GET /api/catalog
static void handleCatalog(const httplib::Request&, httplib::Response& res) {
    ModelCatalog catalog = load_builtin_catalog();
    json models = json::array();
    for (const auto& m : catalog.models) {
        json mj;
        mj["id"] = m.id;
        mj["name"] = m.name;
        mj["family"] = m.family;
        mj["params_billions"] = m.params_billions;
        mj["architecture"] = m.architecture;
        mj["quality_score"] = m.quality_score;
        mj["is_moe"] = m.is_moe;
        mj["max_context"] = m.max_context;
        mj["variant_count"] = (int)m.variants.size();
        models.push_back(mj);
    }
    json data;
    data["models"] = models;
    data["count"] = models.size();
    sendJson(res, 200, makeSuccess(data));
}

// GET /api/models/local
static void handleLocalModels(const httplib::Request&, httplib::Response& res) {
    // Scan common model directories for .gguf files
    json models = json::array();
    const char* dirs[] = {
        "models", "../models", "./models",
        "C:/dev/models", "C:/models"
    };
    for (const char* dir : dirs) {
        if (!fs::exists(dir)) continue;
        for (const auto& entry : fs::directory_iterator(dir)) {
            if (!entry.is_regular_file()) continue;
            std::string ext = entry.path().extension().string();
            // Case-insensitive compare
            for (auto& c : ext) c = (char)tolower(c);
            if (ext != ".gguf") continue;
            json mj;
            mj["path"] = entry.path().string();
            mj["filename"] = entry.path().filename().string();
            mj["size_bytes"] = entry.file_size();
            mj["size_gb"] = entry.file_size() / 1e9;
            models.push_back(mj);
        }
    }
    json data;
    data["models"] = models;
    data["count"] = models.size();
    sendJson(res, 200, makeSuccess(data));
}

// POST /api/download
static void handleDownloadStart(const httplib::Request& req, httplib::Response& res) {
    json body;
    try { body = json::parse(req.body); } catch (...) {
        sendJson(res, 400, makeError("INVALID_JSON", "Request body is not valid JSON"));
        return;
    }

    std::string model_url = body.value("model_url", "");
    if (model_url.empty()) {
        sendJson(res, 400, makeError("MISSING_PARAM", "model_url is required"));
        return;
    }

    // Check if a task is already running
    {
        std::lock_guard<std::mutex> lock(g_task_mutex);
        if (g_task_running) {
            sendJson(res, 409, makeError("BUSY", "Another task is in progress",
                "Active: " + g_active_task_type + " (" + g_active_task_id + ")"));
            return;
        }
        g_task_running = true;
        g_active_task_type = "download";
        g_active_task_id = generateTaskId("dl");
    }

    json data;
    data["task_id"] = g_active_task_id;
    data["stream_url"] = "/api/download/" + g_active_task_id + "/progress";
    sendJson(res, 200, makeSuccess(data));
}

// GET /api/download/:id/progress (SSE)
static void handleDownloadProgress(const httplib::Request& req, httplib::Response& res) {
    std::string task_id;
    auto it = req.path_params.find("id");
    if (it != req.path_params.end()) task_id = it->second;

    if (task_id != g_active_task_id) {
        sendJson(res, 404, makeError("TASK_NOT_FOUND", "No active download with this ID"));
        return;
    }

    sendSSEHeader(res);

    std::string captured_id = task_id;
    res.set_chunked_content_provider("text/event-stream",
        [captured_id](size_t, httplib::DataSink& sink) -> bool {
            if (!g_task_running || g_active_task_id != captured_id) {
                std::string msg = "event: complete\ndata: {\"message\": \"Download complete\"}\n\n";
                sink.write(msg.c_str(), msg.size());
                return false;
            }

            std::string msg = "event: progress\ndata: {\"status\": \"downloading\", \"message\": \"In progress...\"}\n\n";
            bool ok = sink.write(msg.c_str(), msg.size());
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
            return ok;
        });
}

// POST /api/execute
static void handleExecuteStart(const httplib::Request& req, httplib::Response& res) {
    json body;
    try { body = json::parse(req.body); } catch (...) {
        sendJson(res, 400, makeError("INVALID_JSON", "Request body is not valid JSON"));
        return;
    }

    std::string model_path = body.value("model_path", "");
    if (model_path.empty()) {
        sendJson(res, 400, makeError("MISSING_PARAM", "model_path is required"));
        return;
    }

    // Check if file exists
    if (!fs::exists(model_path)) {
        sendJson(res, 404, makeError("FILE_NOT_FOUND", "Model file not found: " + model_path));
        return;
    }

    {
        std::lock_guard<std::mutex> lock(g_task_mutex);
        if (g_task_running) {
            sendJson(res, 409, makeError("BUSY", "Another task is in progress",
                "Active: " + g_active_task_type + " (" + g_active_task_id + ")"));
            return;
        }
        g_task_running = true;
        g_active_task_type = "execute";
        g_active_task_id = generateTaskId("ex");
    }

    json data;
    data["task_id"] = g_active_task_id;
    data["stream_url"] = "/api/execute/" + g_active_task_id + "/stream";
    sendJson(res, 200, makeSuccess(data));
}

// GET /api/execute/:id/stream (SSE)
static void handleExecuteStream(const httplib::Request& req, httplib::Response& res) {
    std::string task_id;
    auto it = req.path_params.find("id");
    if (it != req.path_params.end()) task_id = it->second;

    if (task_id != g_active_task_id) {
        sendJson(res, 404, makeError("TASK_NOT_FOUND", "No active execution with this ID"));
        return;
    }

    sendSSEHeader(res);

    std::string captured_id = task_id;
    res.set_chunked_content_provider("text/event-stream",
        [captured_id](size_t, httplib::DataSink& sink) -> bool {
            auto sendEvent = [&](const std::string& event, const json& data) -> bool {
                std::string msg = "event: " + event + "\ndata: " + data.dump() + "\n\n";
                return sink.write(msg.c_str(), msg.size());
            };

            sendEvent("status", { {"message", "Execution requires CLI: vessel --model <url> --execute"},
                                  {"note", "Web execution coming in a future update"} });

            {
                std::lock_guard<std::mutex> lock(g_task_mutex);
                g_task_running = false;
                g_active_task_type.clear();
                g_active_task_id.clear();
            }

            sendEvent("complete", { {"message", "Dashboard execution not yet implemented. Use CLI."} });
            return false;
        });
}

// POST /api/execute/:id/abort
static void handleExecuteAbort(const httplib::Request& req, httplib::Response& res) {
    std::string task_id;
    auto it = req.path_params.find("id");
    if (it != req.path_params.end()) task_id = it->second;
    if (task_id != g_active_task_id) {
        sendJson(res, 404, makeError("TASK_NOT_FOUND", "No active execution with this ID"));
        return;
    }

    {
        std::lock_guard<std::mutex> lock(g_task_mutex);
        g_task_running = false;
        g_active_task_type.clear();
        g_active_task_id.clear();
    }

    sendJson(res, 200, makeSuccess({ {"message", "Execution aborted"} }));
}

// GET /api/calibration
static void handleCalibration(const httplib::Request&, httplib::Response& res) {
    std::string model_for_fp;
    HardwareSpec hw = profile_hardware(model_for_fp);

    std::string log_path = get_log_path();
    auto records = read_all_records(log_path);

    int match_count = 0;
    for (const auto& r : records) {
        if (r.hardware_fingerprint == hw.hardware_fingerprint) match_count++;
    }

    json data;
    data["records"] = (int)records.size();
    data["matching_records"] = match_count;
    data["fingerprint"] = hw.hardware_fingerprint;
    data["log_path"] = log_path;

    if (match_count > 0) {
        CalibrationAggregator agg(hw.hardware_fingerprint);
        CalibrationData cal = agg.get_calibration_data();
        data["gpu_overhead_mb"] = cal.adjusted_gpu_overhead_bytes / (1024 * 1024);
        data["gpu_decode_efficiency"] = cal.adjusted_gpu_decode_efficiency > 0 ? cal.adjusted_gpu_decode_efficiency : 0.27;
        data["cpu_decode_efficiency"] = cal.adjusted_cpu_decode_efficiency > 0 ? cal.adjusted_cpu_decode_efficiency : 0.80;
        data["gpu_prefill_efficiency"] = cal.adjusted_gpu_prefill_efficiency > 0 ? cal.adjusted_gpu_prefill_efficiency : 0.23;
    }

    sendJson(res, 200, makeSuccess(data));
}

// GET /api/calibration/history
static void handleCalibrationHistory(const httplib::Request& req, httplib::Response& res) {
    std::string log_path = get_log_path();
    auto records = read_all_records(log_path);

    json entries = json::array();
    for (const auto& r : records) {
        json ej;
        ej["hardware_fingerprint"] = r.hardware_fingerprint;
        ej["model_id"] = r.model_id;
        ej["placement"] = r.placement;
        ej["gpu_layers"] = r.gpu_layers;
        ej["context"] = r.context;
        ej["predicted_tps"] = r.predicted_tokens_per_sec;
        ej["actual_tps"] = r.actual_tokens_per_sec;
        ej["predicted_vram"] = r.predicted_vram_bytes;
        ej["actual_vram"] = r.actual_peak_vram_bytes;
        ej["tokens_generated"] = r.actual_tokens_generated;
        ej["timestamp"] = r.timestamp;
        entries.push_back(ej);
    }

    json data;
    data["entries"] = entries;
    data["count"] = (int)entries.size();
    sendJson(res, 200, makeSuccess(data));
}

// DELETE /api/calibration
static void handleCalibrationReset(const httplib::Request&, httplib::Response& res) {
    std::string log_path = get_log_path();
    auto records = read_all_records(log_path);
    int count = (int)records.size();

    if (remove(log_path.c_str()) != 0 && count > 0) {
        sendJson(res, 500, makeError("DELETE_FAILED", "Could not delete calibration log"));
        return;
    }

    sendJson(res, 200, makeSuccess({ {"deleted", count}, {"message", "Calibration log reset"} }));
}

// =============================================================================
// Static File Routes
// =============================================================================
static void setupStaticRoutes(httplib::Server& server) {
    server.Get("/", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_INDEX_HTML, WEB_INDEX_HTML_MIME);
    });
    server.Get("/app.js", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_APP_JS, WEB_APP_JS_MIME);
    });
    server.Get("/styles.css", [](const httplib::Request&, httplib::Response& res) {
        res.set_content(WEB_STYLES_CSS, WEB_STYLES_CSS_MIME);
    });
}

// =============================================================================
// API Routes
// =============================================================================
static void setupApiRoutes(httplib::Server& server) {
    // Health
    server.Get("/api/health", handleHealth);

    // Hardware
    server.Get("/api/hardware", handleHardware);
    server.Get("/api/hardware/live", handleHardwareLive);

    // Predict
    server.Post("/api/predict", handlePredict);

    // Recommendations
    server.Get("/api/recommend", handleRecommend);

    // Catalog
    server.Get("/api/catalog", handleCatalog);
    server.Get("/api/models/local", handleLocalModels);

    // Download
    server.Post("/api/download", handleDownloadStart);
    server.Get("/api/download/:id/progress", handleDownloadProgress);

    // Execute
    server.Post("/api/execute", handleExecuteStart);
    server.Get("/api/execute/:id/stream", handleExecuteStream);
    server.Post("/api/execute/:id/abort", handleExecuteAbort);

    // Calibration
    server.Get("/api/calibration", handleCalibration);
    server.Get("/api/calibration/history", handleCalibrationHistory);
    server.Delete("/api/calibration", handleCalibrationReset);

    // CORS preflight
    server.Options(".*", [](const httplib::Request&, httplib::Response& res) {
        res.set_header("Access-Control-Allow-Origin", "*");
        res.set_header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
        res.set_header("Access-Control-Allow-Headers", "Content-Type");
        res.status = 204;
    });
}

// =============================================================================
// Public API
// =============================================================================
bool start_web_server(int port, const std::string& model_for_fingerprint, bool open_browser_flag) {
    httplib::Server server;

    setupStaticRoutes(server);
    setupApiRoutes(server);

    server.set_error_handler([](const httplib::Request&, httplib::Response& res) {
        sendJson(res, 404, makeError("NOT_FOUND", "Endpoint not found"));
    });

    printf("\n");
    printf("  Vessel Dashboard\n");
    printf("  http://localhost:%d\n", port);
    printf("  Press Ctrl+C to stop\n\n", port);

    if (open_browser_flag) {
        openBrowser("http://localhost:" + std::to_string(port));
    }

    return server.listen("0.0.0.0", port);
}
