# embed_files.cmake - Embeds web assets into C++ string constants at build time
#
# Usage:
#   embed_files(embedded_web.h
#       web/index.html   WEB_INDEX_HTML   text/html
#       web/app.js       WEB_APP_JS       application/javascript
#       web/styles.css   WEB_STYLES_CSS   text/css
#   )
#
#   target_include_directories(mytarget PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
#   target_sources(mytarget PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/embedded_web.h)

function(embed_files OUTPUT_HEADER)
    # Parse arguments: triples of (file_path var_name mime_type)
    set(_files)
    set(_i 0)
    foreach(_arg ${ARGN})
        math(EXPR _mod "${_i} % 3")
        if(_mod EQUAL 0)
            list(APPEND _files "${_arg}")
        elseif(_mod EQUAL 1)
            list(APPEND _files "${_arg}")
        elseif(_mod EQUAL 2)
            list(APPEND _files "${_arg}")
        endif()
        math(EXPR _i "${_i} + 1")
    endforeach()

    set(_header_content "// AUTO-GENERATED by embed_files.cmake - DO NOT EDIT\n#pragma once\n\n")

    set(_idx 0)
    set(_file_paths)
    set(_var_names)
    set(_mime_types)
    while(_idx LESS len(_files))
        list(GET _files ${_idx} _path)
        list(EXPR _idx "${_idx} + 1")
        list(GET _files ${_idx} _var)
        list(EXPR _idx "${_idx} + 1")
        list(GET _files ${_idx} _mime)
        list(EXPR _idx "${_idx} + 1")

        list(APPEND _file_paths "${_path}")
        list(APPEND _var_names "${_var}")
        list(APPEND _mime_types "${_mime}")
    endwhile()

    # Generate the header content
    set(_header_content "${_header_content}// Web asset files embedded at compile time\n\n")

    list(LENGTH _file_paths _count)
    set(_idx 0)
    while(_idx LESS _count)
        list(GET _file_paths ${_idx} _path)
        list(GET _var_names ${_idx} _var)
        list(GET _mime_types ${_idx} _mime)
        list(EXPR _idx "${_idx} + 1")

        file(READ "${_path}" _content)
        string(REPLACE "\\" "\\\\" _content "${_content}")
        string(REPLACE "\"" "\\\"" _content "${_content}")
        string(REPLACE "\n" "\\n\"\n\"" _content "${_content}")

        set(_header_content "${_header_content}static const char* ${_var} = \n\"${_content}\";\nstatic const char* ${_var}_MIME = \"${_mime}\";\n\n")
    endwhile()

    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_HEADER}" "${_header_content}")
    message(STATUS "Embedded ${_count} web assets into ${OUTPUT_HEADER}")
endfunction()
