# embed_files.cmake - Embeds web assets into C++ string constants at build time
#
# Usage:
#   embed_files(embedded_web.h
#       web/index.html   WEB_INDEX_HTML   text/html
#       web/app.js       WEB_APP_JS       application/javascript
#       web/styles.css   WEB_STYLES_CSS   text/css
#   )

function(embed_files OUTPUT_HEADER)
    set(_file_paths)
    set(_var_names)
    set(_mime_types)

    set(_i 0)
    set(_all_args ${ARGN})
    list(LENGTH _all_args _arg_count)

    while(_i LESS _arg_count)
        list(GET _all_args ${_i} _path)
        math(EXPR _i "${_i} + 1")
        list(GET _all_args ${_i} _var)
        math(EXPR _i "${_i} + 1")
        list(GET _all_args ${_i} _mime)
        math(EXPR _i "${_i} + 1")

        list(APPEND _file_paths "${_path}")
        list(APPEND _var_names "${_var}")
        list(APPEND _mime_types "${_mime}")
    endwhile()

    list(LENGTH _file_paths _count)

    # Start building header content
    set(_header "// AUTO-GENERATED by embed_files.cmake - DO NOT EDIT\n#pragma once\n\n")

    set(_idx 0)
    while(_idx LESS _count)
        list(GET _file_paths ${_idx} _path)
        list(GET _var_names ${_idx} _var)
        list(GET _mime_types ${_idx} _mime)

        # Read file content
        file(READ "${_path}" _content)

        # Escape for C++ raw string — use R"DELIM(...)DELIM" syntax
        set(_header "${_header}static const char* ${_var} = R\"EMBED(\n${_content}\n)EMBED\";\nstatic const char* ${_var}_MIME = \"${_mime}\";\n\n")

        math(EXPR _idx "${_idx} + 1")
    endwhile()

    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_HEADER}" "${_header}")
    message(STATUS "Embedded ${_count} web assets into ${OUTPUT_HEADER}")
endfunction()
