# embed_files.cmake - Embeds web assets as hex-encoded C byte arrays
# Avoids MSVC 65535-byte string literal limit

function(embed_files OUTPUT_HEADER)
    set(_file_paths)
    set(_var_names)
    set(_mime_types)

    set(_i 0)
    set(_all_args ${ARGN})
    list(LENGTH _all_args _arg_count)

    while(_i LESS _arg_count)
        list(GET _all_args ${_i} _path)
        math(EXPR _i "${_i} + 1")
        list(GET _all_args ${_i} _var)
        math(EXPR _i "${_i} + 1")
        list(GET _all_args ${_i} _mime)
        math(EXPR _i "${_i} + 1")
        list(APPEND _file_paths "${_path}")
        list(APPEND _var_names "${_var}")
        list(APPEND _mime_types "${_mime}")
    endwhile()

    list(LENGTH _file_paths _count)

    # Start header
    set(_header "// AUTO-GENERATED by embed_files.cmake - DO NOT EDIT\n#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")

    set(_idx 0)
    while(_idx LESS _count)
        list(GET _file_paths ${_idx} _path)
        list(GET _var_names ${_idx} _var)
        list(GET _mime_types ${_idx} _mime)

        # Read file as hex
        file(READ "${_path}" _content HEX)

        # Calculate size (hex has 2 chars per byte)
        string(LENGTH "${_content}" _hex_len)
        math(EXPR _size "${_hex_len} / 2")

        # Build C array: split into lines of 16 bytes
        set(_array "static const uint8_t ${_var}_DATA[] = {\n")
        set(_pos 0)
        set(_byte_count 0)
        while(_pos LESS _hex_len)
            string(SUBSTRING "${_content}" ${_pos} 2 _byte)
            math(EXPR _pos "${_pos} + 2")
            if(_byte_count GREATER 0)
                string(APPEND _array ", ")
            endif()
            string(APPEND _array "0x${_byte}")
            math(EXPR _byte_count "${_byte_count} + 1")
            if(_byte_count EQUAL 16)
                string(APPEND _array ",\n")
                set(_byte_count 0)
            endif()
        endwhile()
        if(_byte_count GREATER 0)
            string(APPEND _array ", ")
        endif()
        string(APPEND _array "0x00};\n")  // null terminator

        # Add accessor as const char*
        set(_array "${_array}static const char* ${_var} = reinterpret_cast<const char*>(${_var}_DATA);\n")
        set(_array "${_array}static const size_t ${_var}_SIZE = ${_size};\n")
        set(_array "${_array}static const char* ${_var}_MIME = \"${_mime}\";\n\n")

        set(_header "${_header}${_array}")
        math(EXPR _idx "${_idx} + 1")
    endwhile()

    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${OUTPUT_HEADER}" "${_header}")
    message(STATUS "Embedded ${_count} web assets into ${OUTPUT_HEADER}")
endfunction()
